import enum

DEFAULT_PORT: int = 4444
MAX_PDU_BYTES: int = 65535
MAX_DECK_SIZE: int = 50
MIN_DECK_SIZE: int = 1
STARTING_LIFE: int = 20
INITIAL_HAND_SIZE: int = 7
MAX_HAND_SIZE: int = 7
PING_INTERVAL_S: int = 30
PONG_TIMEOUT_S: int = 10
DEFAULT_TIME_LIMIT_MS: int = 60_000

#all the error codes that the server can send to the client
class ErrorCode(str, enum.Enum):
    INVALID_JSON = "INVALID_JSON"
    ILLEGAL_DECK = "ILLEGAL_DECK"
    UNKNOWN_TYPE = "UNKNOWN_TYPE"
    STALE_ACTION = "STALE_ACTION"
    NOT_YOUR_PRIORITY = "NOT_YOUR_PRIORITY"
    ILLEGAL_ACTION = "ILLEGAL_ACTION"
    ILLEGAL_TARGET = "ILLEGAL_TARGET"
    TRIGGER_ORDER_INVALID = "TRIGGER_ORDER_INVALID"
    TRIGGER_CHOICE_INVALID = "TRIGGER_CHOICE_INVALID"
    INSUFFICIENT_MANA = "INSUFFICIENT_MANA"
    WRONG_PHASE = "WRONG_PHASE"
    DUPLICATE_ID = "DUPLICATE_ID"


#game phases
IN_GAME_PHASES: list[str] = [
    "UNTAP",
    "UPKEEP",
    "DRAW",
    "PRECOMBAT_MAIN",
    "BEGIN_COMBAT",
    "DECLARE_ATTACKERS",
    "DECLARE_BLOCKERS",
    "ASSIGN_DAMAGE_ORDER",
    "FIRST_STRIKE_DAMAGE",
    "COMBAT_DAMAGE",
    "END_OF_COMBAT",
    "POSTCOMBAT_MAIN",
    "END_STEP",
    "CLEANUP",
]

#lifecycle phases
LIFECYCLE_PHASES: list[str] = [
    "LOBBY",
    "GAME_SETUP",
    "MULLIGAN",
    "GAME_OVER",
]

ALL_PHASES: list[str] = LIFECYCLE_PHASES + IN_GAME_PHASES

# client to server PDUs
C2S_PDU_TYPES: frozenset[str] = frozenset({
    "PLAYER_READY",
    "MULLIGAN_CHOICE",
    "PRIORITY_PASS",
    "CAST_SPELL",
    "ACTIVATE_ABILITY",
    "PLAY_LAND",
    "DECLARE_ATTACKERS",
    "DECLARE_BLOCKERS",
    "ASSIGN_DAMAGE_ORDER",
    "DISCARD",
    "TRIGGER_ORDER_RESPONSE",
    "TRIGGER_CHOICE_RESPONSE",
    "CONCEDE",
    "PING",
})

# Server to client PDUs
S2C_PDU_TYPES: frozenset[str] = frozenset({
    "GAME_STATE_UPDATE",
    "PHASE_TRANSITION",
    "PRIORITY_GRANT",
    "STACK_PUSH",
    "STACK_RESOLVE",
    "TRIGGER_ORDER",
    "TRIGGER_CHOICE",
    "COMBAT_DAMAGE_RESULT",
    "GAME_OVER",
    "ERROR",
    "PONG",
})

ALL_PDU_TYPES: frozenset[str] = frozenset(C2S_PDU_TYPES | S2C_PDU_TYPES)

# priority action PDUs, only works if the sender holds prio
PRIORITY_BEARING_TYPES: frozenset[str] = frozenset({
    "MULLIGAN_CHOICE",
    "PRIORITY_PASS",
    "CAST_SPELL",
    "ACTIVATE_ABILITY",
    "PLAY_LAND",
    "DECLARE_ATTACKERS",
    "DECLARE_BLOCKERS",
    "ASSIGN_DAMAGE_ORDER",
    "DISCARD",
    "TRIGGER_ORDER_RESPONSE",
    "TRIGGER_CHOICE_RESPONSE",
})
